# Generated by Django 2.0.1 on 2018-10-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180612_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
